### ISSUE TITLE
Update Loki version

### ISSUE THREAD

**Issue by AndresSomadossi** [bluemaex/home-assistant-addons#398]
Hello @bluemaex thank you so much for this! I just wonder if is possible to upgrade to the latest version of Loki because this one is missing some feature that grafana tries to use and fails, thanks!

**Comment by bluemaex** [comment]
Hi @AndresSomadossi. I justed released the new versions of the addons :)

**Comment by pdecat** [comment]
Just tried this new version, it fails to start:
```
[13:13:40] INFO: Using default config
[13:13:40] INFO: Retention period set to 30d
[13:13:40] INFO: Loki log level set to info
[13:13:40] INFO: Starting Loki...
[13:13:40] INFO: Handing over control to Loki...
failed parsing config: /etc/loki/default-config.yaml: yaml: unmarshal errors:
  line 21: field max_transfer_retries not found in type ingester.Config
  line 40: field shared_store not found in type boltdb.IndexCfg
  line 46: field shared_store not found in type compactor.Config
  line 55: field max_look_back_period not found in type config.ChunkStoreConfig
[11:13:40] WARNING: Loki exited - Halt add-on with exit code 1
```

**Comment by bluemaex** [comment]
Hmm, thanks for the report.  I will look into that and release an updated version!

**Comment by bluemaex** [comment]
@pdecat So I was looking into this issue today. It looks like in the new major version of loki they discontinued and removed the `boltdb`. There is an entire guide for migration if you want to keep your existing data. Basically you need to migrate from schema v11 to v13 and to the new `tsdb`.

If you do not want to migrate any data you can just create a new configuration file and point to the file in the addon configuration. To save space in your installation I recommend deleting the loki folder in your shared `data` folder.

The following configuration is an example of a new default configuration you could use:

```yaml
---
auth_enabled: false

analytics:
  reporting_enabled: false

server: {}

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s
  wal:
    dir: /data/loki/wal

schema_config:
  configs:
    - from: 2025-06-21
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /data/loki/chunks

compactor:
  working_directory: /data/loki/boltdb-shipper-compactor
  retention_enabled: true
  delete-request-store: filesystem

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: ${RETENTION_PERIOD:29d}
```

I personally did the migration path for my on installation as I also use a different configuration with different storage.
